server:
  port: 8101
spring:
  profiles:
    active: prod
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: jyyx-backend-user-service
       #负载均衡配置
          uri: lb://jyyx-backend-user-service
          predicates:
            - Path=/api/user/**

        - id: jyyx-backend-question-service
      #负载均衡配置
          uri: lb://jyyx-backend-question-service
          predicates:
            - Path=/api/question/**

        - id: jyyx-backend-judge-service
      #负载均衡配置
          uri: lb://jyyx-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: jyyx-backend-gateway
  main:
    web-application-type: reactive

knife4j:
  gateway:
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2

logging:
  level:
    com.schall.jyyxbackendgateway.config: DEBUG
